# Utilizar la imagen de python
FROM python:3.9-slim

# Instalar herramientas de red necesarias
RUN apt-get update && apt-get install -y --no-install-recommends iproute2 && rm -rf /var/lib/apt/lists/*

